---
name: quiltt_connector
description: A Flutter SDK for Quiltt Connector, support iOS and Android.
version: 2.0.2
homepage: https://quiltt.io/
repository: https://github.com/quiltt/quiltt-flutter/tree/main
environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
  webview_flutter: "^4.4.1"
  url_launcher: "^6.1.14"
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
