name: CI

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: "3.0.6"
      - uses: flutter-actions/setup-flutter@v2
        with:
          version: "3.10.6"
          channel: "stable"
          cache: true
          cache-key: ${{ runner.tool_cache }}/flutter # optional, change this to force refresh cache
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.0"

      - name: Install fastlane and dependencies
        run: bundle install

      - name: Check Publish
        run: bundle exec fastlane check_publish

      # In CI, got this error, might be some setup issue, locally it works fine.
      # [!] Your app is using an unsupported Gradle project. To fix this problem, create a new project by running `flutter create -t app <app-directory>` and then move the dart code, assets and pubspec.yaml to the new project.
      # - name: Build Android example app
      #   run: bundle exec fastlane build_example_app
