name: CI

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for authentication using GitHub-signed OIDC token
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: "3.0.6"
      - uses: flutter-actions/setup-flutter@v2
        with:
          version: "3.10.6"
          channel: "stable"
          cache: true
          cache-key: ${{ runner.tool_cache }}/flutter # optional, change this to force refresh cache
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3"

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          # Read https://whichjdk.com/#tldr to understand the difference between different distributions
          # MacOS might be running openjdk 17 (https://whichjdk.com/#apple-silicon) but we want to run the latest LTS on Linux
          distribution: temurin
          java-version: 17

      - name: Install fastlane and dependencies
        run: bundle install

      - name: Build Android example app
        run: bundle exec fastlane build_example_app
