name: Publish to pub.dev

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for authentication using OIDC
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: "3.5.0"
      - uses: flutter-actions/setup-flutter@v2
        with:
          version: "3.24.0"
          channel: "stable"
          cache: true
          cache-key: ${{ runner.tool_cache }}/flutter # optional
      - name: Install dependencies
        run: flutter pub get
      - name: Check Publish Warnings
        run: flutter pub publish --dry-run
      - name: Publish Package
        run: flutter pub publish -f
